apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/peterzal-gmail-com/hack2018:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/peterzal-gmail-com/hack2018:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: hack2018
        chartPath: charts/hack2018
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/peterzal-gmail-com/hack2018"
          image.tag: "{{.TAG}}"
